#ifndef EZUSB_IIDX_SECPLUG_CMD_H
#define EZUSB_IIDX_SECPLUG_CMD_H

enum ezusb_iidx_secplug_dongle_slot {
    EZUSB_IIDX_SECPLUG_DONGLE_SLOT_BLACK = 0x00,
    EZUSB_IIDX_SECPLUG_DONGLE_SLOT_WHITE = 0x01,
};

enum ezusb_iidx_secplug_dongle_memory {
    EZUSB_IIDX_SECPLUG_DONGLE_MEM_ROM = 0x00,
    EZUSB_IIDX_SECPLUG_DONGLE_MEM_DATA = 0x01
};

enum ezusb_iidx_secplug_command_v1 {
    EZUSB_IIDX_SECPLUG_CMD_V1_READ_ROM = 0x01,
    EZUSB_IIDX_SECPLUG_CMD_V1_READ_DATA = 0x02,
    EZUSB_IIDX_SECPLUG_CMD_V1_SECURITY_CONVERSION = 0x03,
    EZUSB_IIDX_SECPLUG_CMD_V1_SELECT_BLACK_DONGLE = 0x04,
    EZUSB_IIDX_SECPLUG_CMD_V1_SELECT_WHITE_DONGLE = 0x05
};

enum ezusb_iidx_secplug_command_status_v1 {
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V1_OK = 0x00,
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V1_FAULT = 0xFE
};

enum ezusb_iidx_secplug_command_v2 {
    EZUSB_IIDX_SECPLUG_CMD_V2_INIT = 0x01,
    EZUSB_IIDX_SECPLUG_CMD_V2_READ_DATA = 0x02,
    EZUSB_IIDX_SECPLUG_CMD_V2_READ_ROM = 0x06,
    EZUSB_IIDX_SECPLUG_CMD_V2_SELECT_WHITE_DONGLE_2 = 0x07,
    EZUSB_IIDX_SECPLUG_CMD_V2_SELECT_BLACK_DONGLE = 0x08,
    EZUSB_IIDX_SECPLUG_CMD_V2_SELECT_WHITE_DONGLE = 0x09
};

enum ezusb_iidx_secplug_command_status_v2 {
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V2_OK = 0x12,
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V2_DATA_OK = 0x13,
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V2_ROM_OK = 0x15,
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V2_SECURITY_SEL_OK = 0x16,
    EZUSB_IIDX_SECPLUG_CMD_STATUS_V2_FAIL = 0xFE
};

#endif