#ifndef EZUSBEMU_NODES_IIDX_H
#define EZUSBEMU_NODES_IIDX_H

#include "ezusb-iidx-emu/node.h"

extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_16seg;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_coin;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_eeprom_v1;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_eeprom_v2;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_fpga_v1;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_fpga_v2;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_none;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_security_mem_v1;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_security_mem_v2;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_security_plug_v1;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_security_plug_v2;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_serial;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_sram;
extern const struct ezusb_iidx_emu_node ezusb_iidx_emu_node_wdt;

#endif
